export const level1Data = [
  {
    a: '친구: 하루 종일 서서 일했더니 허리가 너무 아파.',
    av: 'Bạn: Đứng làm cả ngày nên cái lưng tôi đau quá!',
    b: '__, 고생 많았네. 오늘은 일찍 들어가서 쉬어.',
    bv: '__, Vất vả cho bạn quá. Hôm nay về sớm nghỉ ngơi đi nhé.',
    ans: ['아이구!/아이고!'],
  },
  {
    a: '친구: 이 조그만 가방이 얼마인 줄 알아? 500만 원이래.',
    av: 'Bạn: Cậu biết cái túi nhỏ xíu này bao nhiêu tiền không? Tận 5 triệu won đấy.',
    b: '__, 말도 안 돼! 그게 왜 그렇게 비싸?',
    bv: '__, không thể nào! Sao nó lại đắt thế được?',
    ans: ['대박!'],
  },
  {
    a: '친구: 이 작은 커피 한 잔이 만 원이래.',
    av: 'Bạn: Cái ly cà phê nhỏ xíu này mà bảo là 10 ngàn won đấy.',
    b: '__, 말도 안 돼. 왜 이렇게 비싸?',
    bv: '__, Không thể nào. Sao mà đắt thế được?',
    ans: ['헐'],
  },
  {
    a: '나 요즘 너무 바빠서 청소를 하나도 못 했어.',
    av: 'Bạn: Dạo này tớ bận quá nên chẳng dọn dẹp được tí nào.',
    b: '와... __, 발 디딜 틈이 없다.',
    bv: 'Oa... __, thật vậy luôn (cạn lời). Chẳng có chỗ mà đặt chân nữa.)',
    ans: ['진짜?'],
  },
  {
    a: '친구: 오늘 밖은 영하 10도래. 너무 춥지 않아?',
    av: 'Bạn: Hôm nay thấy bảo là âm 10 độ đấy.',
    b: '응, 바람이 __. 얼굴이 찢어지는 줄 알았어.',
    bv: 'Ừ, gió mạnh __. Tớ tưởng mặt mình bị xé toạc ra luôn.',
    ans: ['장난 아니다'],
  },
  {
    a: '친구: 시험 망했어…',
    av: 'Bạn: Tớ không làm được bài thi/ Tớ làm bài thi không được.',
    b: '__, 진짜 어떡해?',
    bv: '__, làm thế nào bây giờ?)',
    ans: ['와...'],
  },
  {
    a: '친구: 내일도 시험이래.',
    av: 'Bạn: Ngày mai cũng phải thi đấy',
    b: '__, 너무 힘들다..',
    bv: '__, Mệt ghê..',
    ans: ['아, 진짜요?'],
  },
  {
    a: '친구: 더 있어도 재미없어.',
    av: 'Bạn: Ở đây chán quá',
    b: '응, 집에 __.',
    bv: 'Ừ,  về nhà __.',
    ans: ['고고'],
  },
  {
    a: '친구: 발표 어땠어?',
    av: 'Bạn: Bài thuyết trình sao rồi?',
    b: '음..., __.',
    bv: 'Ừm..., __.(chỉ ở mức bình thường)',
    ans: ['나쁘지 않았어'],
  },
  {
    a: '친구: 너무 지쳤어...',
    av: 'Bạn: Mệt quá rồi…',
    b: '그래도 __!',
    bv: '(Dù vậy thì __ chút nữa thôi!)',
    ans: ['파이팅'],
  },
];

export const storyData = {
  ko: {
    story:
      '당신은 한국어 공부를 열심히 했습니다.<br>대학교에서 새로운 한국 친구를 만났어요.<br>친구가 기분이 좋아 보이네요!<br>긍정적인 반응으로 공감해 줍시다.',
    start: '친구에게 다가가기',
    correct: '정답입니다! 잘했어요.',
    wrong: '틀렸습니다! 다시 풀어보세요.',
    gameOverTitle: '게임 오버',
    gameOverDesc: '친구와 사이가 서먹서먹해졌습니다... 😢',
    restart: '다시 도전하기',
  },
  vn: {
    story:
      'Bạn đã chăm chỉ học tiếng Hàn.<br>Bạn gặp một người bạn Hàn Quốc mới tại trường đại học.<br>Bạn của bạn trông có vẻ đang rất vui!<br>Hãy đồng cảm bằng những phản ứng tích cực nhé.',
    start: 'Đến gần bạn của bạn',
    correct: 'Chính xác! Làm tốt lắm.',
    wrong: 'Sai rồi! Hãy thử lại nhé.',
    gameOverTitle: 'Trò chơi kết thúc',
    gameOverDesc: 'Mối quan hệ với bạn bè đã trở nên ngại ngùng... 😢',
    restart: 'Thử lại lần nữa',
  },
};

export const fillerPool = [
  '좋아!',
  '멋지다!',
  '그렇군!',
  '멍청아!',
  '바보',
  '씁..',
  '맞아!',
  '그건 아니야!',
  '너 잘못이야',
  '다시 말해봐',
  '웃기네',
  '너가?',
  '재미있네',
  '지루하네',
  '열받네',
  '안들려',
  '쉽다',
  '거기 서',
];
